### ISSUE TITLE
Doesn't work with wordpress 4.7.3

### ISSUE THREAD

**Issue by rgfx** [uamv/gravity-slider-fields#4]
php 7

Warning: Declaration of GF_Field_Slider::get_value_merge_tag($value, $input_id, $entry, $form, $modifier, $raw_value, $url_encode, $esc_html, $format) should be compatible with GF_Field::get_value_merge_tag($value, $input_id, $entry, $form, $modifier, $raw_value, $url_encode, $esc_html, $format, $nl2br) in C:\xampp\htdocs\rg17\wp-content\plugins\gravity-slider-fields\class-gf-field-slider.php on line 211

**Comment by uamv** [comment]
Version 1.0 fixes this.
